### ISSUE TITLE
Use `obsidian-daily-note-interface` package

### ISSUE THREAD

**Issue by liamcain** [shichongrui/obsidian-rollover-daily-todos#1]
Hi, I think you might benefit from using the `obsidian-daily-note-interface` npm package that I author. It reads the entire daily note config and sanitizes it so it might simplify your code a bit. 

It also uses the configured Daily Note format which seems to be missing from your code.

Let me know if you have any questions!

**Comment by KjellConnelly** [comment]
@liamcain Hey hey! Thanks for writing that library :) I added it, and it's very helpful 😄
