### ISSUE TITLE
Configurable Daily Notes Path

### ISSUE THREAD

**Issue by shawnduggan** [shichongrui/obsidian-rollover-daily-todos#14]
I use Periodic Notes and not the core Daily Notes plugin. I don't want to have the Daily Notes plugin enabled. Can you allow the path to the Daily Notes folder to be manually configured?

**Comment by KjellConnelly** [comment]
I'll write a pull request for this later today

**Comment by KjellConnelly** [comment]
@shawnduggan I just released version `1.0.5` which now works with the `Daily Notes plugin` as well as the `Periodic Notes plugin`. Path to Daily Notes still can't be manually configured, but as long as you are using Periodic Notes, and not trying to roll your own solution, things are all good now :)
