### ISSUE TITLE
Tasks do not roll over when using mobile (android)

### ISSUE THREAD

**Issue by iroQuai** [shichongrui/obsidian-rollover-daily-todos#15]
This plugin is fantastic! Problem is that on mobile it doesn't work (only when I create a new daily note from windows).
I use android with obsidian 0.1.1

**Comment by KjellConnelly** [comment]
Hi @iroQuai, I *may* have fixed this issue. It didn't work on iPhone for me until I updated the code. Try it again with version `1.0.5`. I assume it'll work now, but please reopen this issue if it doesn't.
