### ISSUE TITLE
Plugin settings turn blank

### ISSUE THREAD

**Issue by ONLYA** [shichongrui/obsidian-rollover-daily-todos#17]
When I start Obsidian (I have created daily notes for today yesterday), the unchecked to-do's does not append to the heading, which is expected. When I open the settings to check the plugin settings, I find that **ONLY** this page turns totally blank.
![image](https://user-images.githubusercontent.com/36487580/122769714-b6e31a80-d29c-11eb-8cd3-ef64a5901847.png)

The workaround I have done:
- I have deleted the existed note and create a new one, the unchecked to-dos do not show up.
- I re-installed the plugin, the plugin setting still remains blank.
- I have restarted Obsidian many times, the plugin settings still remains blank.
- I created a new vault. The plugin settings appear eventually.

Is this a bug with this plugin or with Obsidian?

**Comment by ONLYA** [comment]
Well, now I manually created a daily note for yesterday for testing. When I set it up and open today's note, there are no rolled to-do s from the last note. When I install the Calendar plugin and create a note for tomorrow, there are no rolled to-dos from today's one. I began to question how could this plugin work...

**Comment by villers** [comment]
i have the same problem

**Comment by Chris8031** [comment]
I also have the same problem

**Comment by arinazari** [comment]
I don't even see the plug-settings.

**Comment by stouf** [comment]
> I don't even see the plug-settings.

Same thing for me 😞

**Comment by stouf** [comment]
https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/18

I tried these changes against my vault and they seem to work. I can now see the plugin settings and the plugin behaves as I expect it to.

**Comment by wenliang** [comment]
Thanks @stouf . Hope this will be merged soon.

**Comment by fglazer** [comment]
> > I don't even see the plug-settings.
> 
> Same thing for me 😞

I don't see plug-in settings either, and new daily note is not capturing the unfinished tasks.

**Comment by stouf** [comment]
> > > I don't even see the plug-settings.
> > 
> > 
> > Same thing for me 😞
> 
> I don't see plug-in settings either, and new daily note is not capturing the unfinished tasks.

If I understood correctly, a recent change in the API of Obsidian breaks the plugin when it starts up. That's you can't even see the settings entry. That's actually where it crashes, preventing the rest from running 😅

**Comment by stouf** [comment]
@shichongrui Any news/ideas on this? 😅

**Comment by shichongrui** [comment]
Is this still a problem in version 1.0.3?

**Comment by stouf** [comment]
@shichongrui I just tried and confirmed the version 1.0.3 of the plugin works 👍

https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/21 apparently successfully fixed it 🎉 I would be careful with [this](https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/21#issuecomment-903017149) however 😅

**Comment by KjellConnelly** [comment]
Hopefully their API doesn't change, or it'll need to be fixed again :)

**Comment by KjellConnelly** [comment]
Hopefully their API doesn't change, or it'll need to be fixed again :)
