### ISSUE TITLE
not operating…

### ISSUE THREAD

**Issue by lwb52** [shichongrui/obsidian-rollover-daily-todos#2]
using latest insider ObsidianMD, the plugin does not place still-open daily note to-dos (from the note created by that other plugin) into the new, next day’s, daily note (again using that same plugin) at _any_ place in the new note, including the new note's template section as specified in the rollover plugin settings…
any suggestion?

**Comment by vamfoom** [comment]
I have the same problem.

**Comment by ConorMatthews** [comment]
Yep, got the same problem here as well. Was really enjoying using it as well :(

**Comment by OliverAndrews** [comment]
The API for Obsidian looks like it changed the way the filesystem works. Going through the code, this code will not run in new Obsidian API system. I have made update code here with this as inspiration. Feel free to use and let me know of bugs.

**Comment by lwb52** [comment]
sorry to report it still does not work, under the latest insider version :^(

**Comment by OliverAndrews** [comment]
@lwb52 I have made updates to the code and installation instructions. Original ones contained error. Note that I am talking about the Iris plugin, not this one here.

**Comment by shichongrui** [comment]
Closing in favor of #3 as it is the same issue.
