### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by shichongrui** [shichongrui/obsidian-rollover-daily-todos#22]
I just don't have enough time to keep up with the rapid changes in obsidian and obviously, this is negatively affecting many users of the plugin so if there is someone who would like to contribute. I will make them a contributor.

**Comment by KjellConnelly** [comment]
Hey @shichongrui, I'll be making a pull request a bit later today which will fix some issues, add new options, simplify the code, and add a readme. Can you add me as a contributor?

**Comment by shichongrui** [comment]
@KjellConnelly Thank you. Sent an invite.

**Comment by KjellConnelly** [comment]
Feel free to reopen if you'd like more maintainers :) Just trying to get rid of open issues/pull requests.
