### ISSUE TITLE
getISOFormattedDate doesn't work with custom Daily notes date format

### ISSUE THREAD

**Issue by danielbcorreia** [shichongrui/obsidian-rollover-daily-todos#24]
The core Daily notes plugin supports setting a custom date format, in my case that would be `YYYY-MM-DD dddd` (it includes the day of the week).

This plugin however checks the filename by using the getISOFormattedDate which would always return `YYYY-MM-DD`:
https://github.com/shichongrui/obsidian-rollover-daily-todos/blob/master/index.js#L54

The solution can be to read the Daily notes plugin setting and using momentjs (which is what Obsidian uses) to render the date instead of doing it manually.

**Comment by KjellConnelly** [comment]
Fixed in new release `1.0.5`
