### ISSUE TITLE
Sometimes daily todos will rollover twice

### ISSUE THREAD

**Issue by howardhhm** [shichongrui/obsidian-rollover-daily-todos#31]
OS：Mac
I name the first rollover, normal rollover. And the second rollover, shadow rollover.

If I delete the daily note and renew another one, the bug will appear. Shadow rollover always comes after normal  rollover about a few seconds.

And I tried disabling the safe mode without disabling the plugin first, strangely the shadow rollover comes. I am sure that is the plugin operations because the todos appear at the header level which I specified.

If I tried disabling the safe mode after disabling the plugin first, the shadow rollover will disappear.

It nearly drives me mad.😭

**Comment by cjmabry** [comment]
Are you using Obsidian Sync per chance? I've been getting similar behavior which I think is due to opening my notes on one computer, and then looking at them on another, although it's possible this is a separate issue - I need to create some easy steps to reproduce.

**Comment by howardhhm** [comment]
You are right. I have a Mac mini at home, and I work on a MacBook Pro. Obsidian Sync bases on iCloud. I tried quitting Obsidian when I leave, the issue does not reproduce any more. However it is inconvenience to users. I hope the issue can be solved.

THX.

Sent with a Spark
在 2021年10月1日 +0800 01:08，Chris Mabry ***@***.***>，写道：

**Comment by cjmabry** [comment]
Whoops, I accidentally deleted my comment. Reposting here so @howardhhm's reply makes sense.

> Are you using Obsidian Sync per chance? I've been getting similar behavior which I think is due to opening my notes on one computer, and then looking at them on another, although it's possible this is a separate issue - I need to create some easy steps to reproduce.

I'll see if I'm able to consistently reproduce.

**Comment by cjmabry** [comment]
@howardhhm in the meantime, this workaround from the known bugs in the README might help:

> Sometimes, if you trigger the rollover function too quickly, it will read the state of a file before the new data was saved to disk. For example, if you add a new incomplete todo to yesterday's daily note, and then quickly run the Rollover Todos Now command, it may grab the state of the file a second or two before you ran the command. If this happens, just run the Undo last rollover command. Wait a second or two, then try rolling over todos again.

**Comment by howardhhm** [comment]
@cjmabry I see. There is no need to post an issue since it is a known bug. Thx~~
