### ISSUE TITLE
why did not run？

### ISSUE THREAD

**Issue by daytang** [shichongrui/obsidian-rollover-daily-todos#4]
very useful funtion！

but it can't work！

hope tu update the plugin，thank

**Comment by OliverAndrews** [comment]
Obsidian API looks like it has had breaking change. Looking at source, this plugin is calling library methods wrong, probably a result of this. As it stands, this plugin _does not work_. I have a reimplementation of this [here](https://github.com/OliverAndrews/ObsidianIris).

**Comment by daytang** [comment]
so nice of you!wish you success!发自我的华为手机-------- 原始邮件 --------发件人： Oliver Andrews <notifications@github.com>日期： 2021年1月4日周一 清晨6:26收件人： shichongrui/obsidian-rollover-daily-todos <obsidian-rollover-daily-todos@noreply.github.com>抄送： daytang <69802300@qq.com>, Author <author@noreply.github.com>主    题： Re: [shichongrui/obsidian-rollover-daily-todos] why did not run？ (#4)
Obsidian API looks like it has had breaking change. Looking at source, this plugin is calling library methods wrong, probably a result of this. As it stands, this plugin does not work. I have a reimplementation of this here.

**Comment by OliverAndrews** [comment]
Obsidian API looks like it has had breaking change. Looking at source, this plugin is calling library methods wrong, probably a result of this. As it stands, this plugin does not work. I have a reimplementation of this [here](https://github.com/OliverAndrews/ObsidianIris).

**Comment by shichongrui** [comment]
Closing this issue in favor of #3 as it is the same issue.
