### ISSUE TITLE
Add command to manually run

### ISSUE THREAD

**Issue by sford-square** [shichongrui/obsidian-rollover-daily-todos#7]
Thanks for this great plugin! I'm requesting an augmentation that allows me to manually run the plugin. Sometimes, I'll create a daily note for a future day using the calendar plugin. When the day comes up, it will not inherit the todos from the previous day. A simple command that, when run from the current daily note, will pick off the unchecked todos from the previous day would help immensely!

Thanks for your consideration!

**Comment by tgrosinger** [comment]
@sford-square It looks like this plugin has not been updated for a while, so I wanted to let you know that I have recently added similar functionality to [Slated](https://github.com/tgrosinger/slated-obsidian), and it can be run by a manual command. Check out the demo screencast in the Readme.

**Comment by KjellConnelly** [comment]
Hi @sford-square, I just added this feature in release `1.0.5`. It only rolls todos to the **Today Daily Note** (based off of your device's date), from the note chronologically prior to the **Today Daily Note**.

Ie: Today is Wednesday, and you have a note from yesterday with todos. Anywhere you are in Obsidian will move todos from Tuesday's to today's daily note.

Likewise, if you have daily notes on Monday, Wednesday (Today is Wednesday again in this hypothetical), and a future note for Friday. And no matter where you are in Obsidian (editor open on Friday/Wednesday/Monday's daily note or anywhere else), todos will be rolled over from Monday's Daily Note to Wednesday's Daily Note.
