### ISSUE TITLE
Preserve indentation

### ISSUE THREAD

**Issue by iwaldrop-gsn** [shichongrui/obsidian-rollover-daily-todos#8]
I typically have several nested tasks, and when they're rolled over the hierarchy gets flattened, leading to a bit of manual effort.

On my end I just updated the regex used to find them, preserving whitespace:
```js
const unfinishedTodosRegex = /\t*- \[ \].*/g;
```

**Comment by shichongrui** [comment]
Feel free to open a PR and I can get it in.

**Comment by ianwaldrop** [comment]
https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/9
